### ISSUE TITLE
birdie won't start on latest mobian bookworm

### ISSUE THREAD

**Issue by mbohun** [Dejvino/birdie#10]
```
mobian@mobian:~$ birdie
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mpris_server/types.py", line 5, in <module>
    from typing import \
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/lib/python3.9/typing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/birdie", line 375, in <module>
    from mpris_server.adapters import MprisAdapter
  File "/usr/local/lib/python3.9/dist-packages/mpris_server/__init__.py", line 1, in <module>
    from . import adapters, base, types, server, mpris, interfaces
  File "/usr/local/lib/python3.9/dist-packages/mpris_server/adapters.py", line 5, in <module>
    from .base import URI, MIME_TYPES, PlayState, DEFAULT_RATE, Microseconds, \
  File "/usr/local/lib/python3.9/dist-packages/mpris_server/base.py", line 10, in <module>
    from .types import TypedDict, TypeAlias, \
  File "/usr/local/lib/python3.9/dist-packages/mpris_server/types.py", line 11, in <module>
    from typing_extensions import \
ImportError: cannot import name '_GenericAlias' from 'typing_extensions' (/usr/local/lib/python3.9/dist-packages/typing_extensions.py)
```

This is on PinePhone1.2 running the most recent mobian bookworm
```
mobian@mobian:~$ cat /etc/*rel*
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
mobian@mobian:~$ uname -a
Linux mobian 5.15-sunxi64 #1 SMP Fri Jan 7 23:54:31 UTC 2022 aarch64 GNU/Linux
```

**Comment by Dejvino** [comment]
Thanks for reporting. Looks like `mpris_server` doesn't work with the distribution's `typing_extensions 4.0.1`, it works with `typing-extensions 3.10.0.0`

**Comment by Dejvino** [comment]
Resolved in v0.2.1 by forcing `typing-extensions 3.10.0.2` (the last version that worked) when using Python 3.9
Not affecting Python 3.10+
